CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 accelerate launch --config_file sft2.yaml src/train_bash.py \
    --stage sft \
    --model_name_or_path /home/ubuntu/huggingface/Baichuan2-13B-Base \
    --do_train \
    --dataset system_role,general_med_books,medsci_data,huatuo_sft_v1_,doctor_patient_qa,CHIP_PromptCBLUE_train,CHIP_YIER_train,LongBench \
    --template bianque \
    --cutoff_len 3200 \
    --finetuning_type lora \
    --lora_target W_pack,o_proj,gate_proj,up_proj,down_proj \
    --output_dir Baichuan2_save_sft_v5 \
    --overwrite_cache \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.1 \
    --logging_steps 10 \
    --save_steps 10000 \
    --learning_rate 1.25e-4 \
    --num_train_epochs 4.0 \
    --plot_loss \
    --bf16 True \
    --fp16 False